Homework 3
==========

In this homework...


* Model experimental data of the mobility versus field and temperature for conjugated polymer materials using multivariable linear regression
* Assess the goodness of fit of linear models

Problem statement
-----------------------
1. Plot the square root of the electric field $\left(\sqrt{F}\right)$ versus the mobility $\left(\mu_H\right)$ for data points only at temperatures of 173, 273, and 343 K. Plot all three on the same plot and include a legend denoting which points are at which temperature.


2. Perform a multi-variable linear regression to predict $\log_{10}(\mu_{H})$ from the variables $\sqrt{F} / T^{2}$ and $1/T^{2}$ using $\textit{all}$ of the data (i.e., data at all temperatures should be used to fit the linear regression). Create a copy of the same plot from part 1 (again only temperatures 173, 273, and 343 K), and now add lines of best fit from this linear regression model.

    
3. Find the $R^2$ value of each of the 3 linear fits described above. ($\textbf{Note:}$ This can be done with the function sklearn.metrics.r2_score(). You can use Google to find the documentation of this function if you are unfamiliar.) Clearly report the $R^2$ values of each temperature.


4. Again perform a multi-variable linear regression to predict $\log_{10}(\mu_{H})$ from the variables $\sqrt{F} / T^{2}$ and $1/T^{2}$ using $\textit{only data at or above a temperature of 273 K}$. Create a copy of the same plot from part 2 (only temperatures 173, 273, and 343 K), and add lines of best fit from this linear regression model. Report $R^2$ values for each fit.


5. Pick a new temperature besides 173, 273, or 343 K. Repeat the analysis from part 4, with the following changes:
    - Only plot the data and linear fit of your chosen temperature
    - Use a different range of 7 temperatures to train the linear model (besides those at 273 K or above - for example, you could train the model on temperatures at or below 243 K)
    - Report what temperature range you used for training and the $R^2$ value of the fit
    - Repeat this 3 more times with different temperature ranges (you should have 4 total temperature ranges, plots, and $R^2$ values


Import the necessary modules

In [1]:
import numpy as np
import sys
sys.path.append('../')
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.metrics import r2_score
from sklearn import linear_model
import sklearn.metrics as metrics

Load the data [extracted from Fig 4 of Laquai, Frederic, Gerhard Wegner, and Heinz Bässler. "What determines the mobility of charge carriers in conjugated polymers?." Philosophical Transactions of the Royal Society A: Mathematical, Physical and Engineering Sciences 365.1855 (2007): 1473-1487.]

In [2]:
file_name = 'data/conjpoly_mobility.csv'
names = ["field","temperature","mobility"]
data = pd.read_csv(file_name, header=None, names=names)
field = data.loc[:,"field"]
temperature = data.loc[:,"temperature"]
mobility = 10**data.loc[:,"mobility"]
alltemps = data.temperature.unique()
print(alltemps)

[173.  183.  203.  213.  223.  233.  243.  253.  263.  273.  296.6 303.
 313.  323.  333.  343. ]


1. Plot the square root of the electric field $\left(\sqrt{F}\right)$ versus the mobility $\left(\mu_H\right)$ for data points only at temperatures of 173, 273, and 343 K. Plot all three on the same plot and include a legend denoting which points are at which temperature.

2. Perform a multi-variable linear regression to predict $\log_{10}(\mu_{H})$ from the variables $\sqrt{F} / T^{2}$ and $1/T^{2}$ using $\textit{all}$ of the data (i.e., data at all temperatures should be used to fit the linear regression). Create a copy of the same plot from part 1 (again only temperatures 173, 273, and 343 K), and now add lines of best fit from this linear regression model.

3. Find the $R^2$ value of each of the 3 linear fits described above. ($\textbf{Note:}$ This can be done with the function sklearn.metrics.r2_score(). You can use Google to find the documentation of this function if you are unfamiliar.) Clearly report the $R^2$ values of each temperature.

4. Again perform a multi-variable linear regression to predict $\log_{10}(\mu_{H})$ from the variables $\sqrt{F} / T^{2}$ and $1/T^{2}$ using $\textit{only data at or above a temperature of 273 K}$. Create a copy of the same plot from part 2 (only temperatures 173, 273, and 343 K), and add lines of best fit from this linear regression model. Report $R^2$ values for each fit.

5. Pick a new temperature besides 173, 273, or 343 K. Repeat the analysis from part 4, with the following changes:
    - Only plot the data and linear fit of your chosen temperature
    - Use a different range of 7 temperatures to train the linear model (besides those at 273 K or above - for example, you could train the model on temperatures at or below 243 K)
    - Report what temperature range you used for training and the $R^2$ value of the fit
    - Repeat this 3 more times with different temperature ranges (you should have 4 total temperature ranges, plots, and $R^2$ values
